[package]
name = "ring3-core"
description = "Rust and WebAssembly core for ring3."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
iced-x86 = { version = "=1.21.0", default-features = false, features = ["std", "decoder"] }
sha2 = { version = "=0.11.0", default-features = false }
